// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCot3LHEgpmovLOHTjd5DOi_g2KQ96-Zu4',
    appId: '1:1022876601447:web:31e94a0c2f9eec11cc98c2',
    messagingSenderId: '1022876601447',
    projectId: 'congregate-13607',
    authDomain: 'congregate-13607.firebaseapp.com',
    storageBucket: 'congregate-13607.firebasestorage.app',
    measurementId: 'G-57LG9L9KW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSCXhRM-JSb76Kp_0hYXa4PPnFYcZksiY',
    appId: '1:1022876601447:android:eb1c55c9a1b4be4ecc98c2',
    messagingSenderId: '1022876601447',
    projectId: 'congregate-13607',
    storageBucket: 'congregate-13607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ecN-_Geq6eVqTfX9R7QkYu31Qa_wbu0',
    appId: '1:1022876601447:ios:9e502fddce064a58cc98c2',
    messagingSenderId: '1022876601447',
    projectId: 'congregate-13607',
    storageBucket: 'congregate-13607.firebasestorage.app',
    androidClientId: '1022876601447-572f99te954ldsrquheo8lsce3kavuhk.apps.googleusercontent.com',
    iosClientId: '1022876601447-3p7l1qu23p52u0phmkhth0oa4ui8i3go.apps.googleusercontent.com',
    iosBundleId: 'com.qubique.congregate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ecN-_Geq6eVqTfX9R7QkYu31Qa_wbu0',
    appId: '1:1022876601447:ios:9e502fddce064a58cc98c2',
    messagingSenderId: '1022876601447',
    projectId: 'congregate-13607',
    storageBucket: 'congregate-13607.firebasestorage.app',
    androidClientId: '1022876601447-572f99te954ldsrquheo8lsce3kavuhk.apps.googleusercontent.com',
    iosClientId: '1022876601447-3p7l1qu23p52u0phmkhth0oa4ui8i3go.apps.googleusercontent.com',
    iosBundleId: 'com.qubique.congregate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCot3LHEgpmovLOHTjd5DOi_g2KQ96-Zu4',
    appId: '1:1022876601447:web:c99ccf44ee79eb7acc98c2',
    messagingSenderId: '1022876601447',
    projectId: 'congregate-13607',
    authDomain: 'congregate-13607.firebaseapp.com',
    storageBucket: 'congregate-13607.firebasestorage.app',
    measurementId: 'G-2GGQ9VVG78',
  );

}